# Generated by Django 5.2.17 on 2026-10-02 17:55

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='Baslik')),
                ('advertiser', models.CharField(blank=True, max_length=120, verbose_name='Reklamveren')),
                ('image', models.ImageField(upload_to='banners/', verbose_name='Gorsel')),
                ('link_url', models.CharField(blank=True, max_length=300, verbose_name='Tiklayinca gidilecek adres')),
                ('place', models.CharField(choices=[('home_hero', 'Ana sayfa ust kaydirici (1400x420 onerilir)'), ('home_mid', 'Ana sayfa orta serit (600x300 onerilir, en fazla 3)')], default='home_hero', max_length=12, verbose_name='Alan')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Sira')),
                ('is_active', models.BooleanField(default=True, verbose_name='Yayinda')),
                ('starts_at', models.DateTimeField(blank=True, null=True, verbose_name='Baslangic')),
                ('ends_at', models.DateTimeField(blank=True, null=True, verbose_name='Bitis')),
                ('clicks', models.PositiveIntegerField(default=0, editable=False, verbose_name='Tiklama')),
            ],
            options={
                'verbose_name': 'Reklam banner',
                'verbose_name_plural': 'Reklam bannerlari',
                'ordering': ['place', 'order', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('code', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('name_local', models.CharField(max_length=60)),
                ('name_tr', models.CharField(max_length=60)),
                ('name_en', models.CharField(max_length=60)),
                ('flag', models.CharField(max_length=8)),
                ('lang', models.CharField(default='en', max_length=5)),
                ('currency', models.CharField(max_length=3)),
                ('symbol', models.CharField(max_length=6)),
                ('rate_per_eur', models.DecimalField(decimal_places=4, default=1, max_digits=12)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'countries',
                'ordering': ['order', 'code'],
            },
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True)),
                ('percent_off', models.PositiveSmallIntegerField(blank=True, help_text='orn. 20 -> %20 indirim', null=True)),
                ('amount_off_eur', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('active', models.BooleanField(default=True)),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
                ('max_uses', models.PositiveIntegerField(blank=True, null=True)),
                ('used_count', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_image', models.ImageField(blank=True, help_text='Bos birakilirsa varsayilan cizim banner kullanilir. Genis (en az 1600 px) bir fotograf onerilir.', null=True, upload_to='site/', verbose_name='Ana sayfa banner gorseli')),
            ],
            options={
                'verbose_name': 'Site ayari',
                'verbose_name_plural': 'Site ayarlari',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('used', 'Ikinci el'), ('shop', 'Magaza')], max_length=8)),
                ('slug', models.SlugField(max_length=80)),
                ('icon', models.CharField(blank=True, max_length=8)),
                ('names', models.JSONField(default=dict, help_text='{"tr": "...", "en": "...", ...}')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='market.category')),
            ],
            options={
                'verbose_name_plural': 'categories',
                'ordering': ['order', 'id'],
                'unique_together': {('mode', 'parent', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='market.country')),
            ],
            options={
                'verbose_name_plural': 'cities',
                'ordering': ['order', 'name'],
                'unique_together': {('country', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('used', 'Ikinci el'), ('shop', 'Magaza')], db_index=True, max_length=8)),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220)),
                ('description', models.TextField(blank=True)),
                ('price_eur', models.DecimalField(decimal_places=2, max_digits=12)),
                ('image', models.ImageField(blank=True, null=True, upload_to='listings/')),
                ('featured_until', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('track_stock', models.BooleanField(default=False, help_text='Acilirsa stok adedi tukeninceye kadar satisa acik kalir')),
                ('stock', models.PositiveIntegerField(blank=True, help_text='track_stock acikken gecerli', null=True)),
                ('seller_name', models.CharField(blank=True, max_length=80)),
                ('seller_phone', models.CharField(blank=True, max_length=32)),
                ('condition', models.CharField(choices=[('new', 'Sifir'), ('used', 'Ikinci el')], default='used', max_length=8)),
                ('delivery', models.CharField(choices=[('ship', 'Kargo'), ('hand', 'Elden teslim')], default='hand', max_length=8)),
                ('free_shipping', models.BooleanField(default=False)),
                ('icon', models.CharField(blank=True, max_length=8)),
                ('hue', models.PositiveSmallIntegerField(default=190)),
                ('rating', models.DecimalField(decimal_places=1, default=5, max_digits=3)),
                ('favorites', models.PositiveIntegerField(default=0)),
                ('views', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('category', models.ForeignKey(help_text='Alt kategori secilir', on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='market.category')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='market.city')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='market.country')),
                ('owner', models.ForeignKey(blank=True, help_text='Bireysel (ikinci el) ilanin sahibi', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='my_listings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('participant_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conv_a', to=settings.AUTH_USER_MODEL)),
                ('participant_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conv_b', to=settings.AUTH_USER_MODEL)),
                ('listing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversations', to='market.listing')),
            ],
            options={
                'ordering': ['-updated_at'],
                'unique_together': {('listing', 'participant_a', 'participant_b')},
            },
        ),
        migrations.CreateModel(
            name='Boost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days', models.PositiveSmallIntegerField()),
                ('price_eur', models.DecimalField(decimal_places=2, max_digits=8)),
                ('status', models.CharField(choices=[('pending', 'Beklemede'), ('paid', 'Odendi')], default='pending', max_length=10)),
                ('stripe_session_id', models.CharField(blank=True, max_length=200)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boosts', to=settings.AUTH_USER_MODEL)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boosts', to='market.listing')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ListingImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='listings/gallery/')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='market.listing')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ListingVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="orn. 'Kırmızı / M'", max_length=60)),
                ('price_delta_eur', models.DecimalField(decimal_places=2, default=0, help_text='Ana fiyata eklenir/cikarilir, orn. -2.00', max_digits=8)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('sku', models.CharField(blank=True, max_length=40)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='market.listing')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='market.conversation')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Beklemede'), ('paid', 'Odendi'), ('cancelled', 'Iptal')], default='pending', max_length=10)),
                ('total_eur', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('full_name', models.CharField(blank=True, max_length=120)),
                ('address', models.CharField(blank=True, max_length=240)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('stripe_session_id', models.CharField(blank=True, max_length=200)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('discount_eur', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='market.country')),
                ('coupon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='market.coupon')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('variant_name', models.CharField(blank=True, max_length=60)),
                ('price_eur', models.DecimalField(decimal_places=2, max_digits=12)),
                ('qty', models.PositiveSmallIntegerField(default=1)),
                ('carrier', models.CharField(blank=True, max_length=60)),
                ('tracking_number', models.CharField(blank=True, max_length=80)),
                ('shipped_at', models.DateTimeField(blank=True, null=True)),
                ('listing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='market.listing')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='market.order')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='market.listingvariant')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField()),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='market.listing')),
                ('order_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='market.orderitem')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(blank=True, max_length=140, unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='shops/')),
                ('about', models.TextField(blank=True)),
                ('hue', models.PositiveSmallIntegerField(default=190)),
                ('rating', models.DecimalField(decimal_places=1, default=5, max_digits=3)),
                ('sales', models.PositiveIntegerField(default=0)),
                ('verified', models.BooleanField(default=False)),
                ('plan', models.CharField(choices=[('trial', 'Ilk 3 ay ucretsiz'), ('mid', '9 EUR / ay'), ('full', '29 EUR / ay')], default='trial', max_length=8)),
                ('opened_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shops', to='market.category')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='market.city')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shops', to='market.country')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shops', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-verified', '-rating', 'name'],
            },
        ),
        migrations.AddField(
            model_name='orderitem',
            name='shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='market.shop'),
        ),
        migrations.AddField(
            model_name='listing',
            name='shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='market.shop'),
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL)),
                ('listing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='market.listing')),
                ('shop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='market.shop')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='coupon',
            name='shop',
            field=models.ForeignKey(blank=True, help_text='Bossa tum magazalarda gecerli', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coupons', to='market.shop'),
        ),
        migrations.CreateModel(
            name='ShopApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.CharField(max_length=120)),
                ('contact_name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('tax_number', models.CharField(blank=True, max_length=40)),
                ('website', models.URLField(blank=True)),
                ('about', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Beklemede'), ('approved', 'Onaylandi'), ('rejected', 'Reddedildi')], default='pending', max_length=10)),
                ('staff_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shop_applications', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(blank=True, limit_choices_to={'mode': 'shop', 'parent__isnull': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='market.category')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='market.city')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='market.country')),
                ('shop', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='application', to='market.shop')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['mode', 'country', 'category'], name='market_list_mode_72b9d8_idx'),
        ),
        migrations.AddConstraint(
            model_name='favorite',
            constraint=models.UniqueConstraint(condition=models.Q(('listing__isnull', False)), fields=('user', 'listing'), name='uniq_fav_listing'),
        ),
        migrations.AddConstraint(
            model_name='favorite',
            constraint=models.UniqueConstraint(condition=models.Q(('shop__isnull', False)), fields=('user', 'shop'), name='uniq_fav_shop'),
        ),
    ]
