# Generated by Django 5.2.17 on 2026-10-04 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(unique=True, verbose_name='Gun')),
                ('visitors', models.PositiveIntegerField(default=0, verbose_name='Tekil ziyaretci')),
                ('pageviews', models.PositiveIntegerField(default=0, verbose_name='Sayfa goruntuleme')),
            ],
            options={
                'verbose_name': 'Gunluk istatistik',
                'verbose_name_plural': 'Gunluk istatistikler',
                'ordering': ['-day'],
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='Baslik')),
                ('slug', models.SlugField(max_length=140, unique=True, verbose_name='Adres (slug)')),
                ('body', models.TextField(help_text='Duz metin. Bos satir yeni paragraf olur.', verbose_name='Icerik')),
                ('group', models.CharField(choices=[('f1', 'Kurumsal sutunu'), ('f2', 'Yardim sutunu')], default='f1', max_length=2, verbose_name='Alt bilgide yeri')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Sira')),
                ('is_published', models.BooleanField(default=True, verbose_name='Yayinda')),
            ],
            options={
                'verbose_name': 'Sayfa',
                'verbose_name_plural': 'Sayfalar',
                'ordering': ['group', 'order', 'title'],
            },
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='address',
            field=models.TextField(blank=True, verbose_name='Adres'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='company_name',
            field=models.CharField(blank=True, help_text='Alt bilgide (c) satirinda gorunur.', max_length=160, verbose_name='Sirket adi'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='E-posta'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='phone',
            field=models.CharField(blank=True, max_length=40, verbose_name='Telefon'),
        ),
    ]
