# Generated by Django 5.2.17 on 2026-10-05 18:35

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_dailystat_page_sitesettings_address_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='listings/video/', verbose_name='Video (mp4/webm, en fazla 50 MB)'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(default='card', max_length=10),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='seo_description',
            field=models.CharField(blank=True, help_text='Basligin altindaki tanitim yazisi, 150-160 karakter ideal.', max_length=170, verbose_name='Google aciklamasi (ana sayfa)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='seo_title',
            field=models.CharField(blank=True, help_text='Google sonucunda mavi baslik olarak gorunur. Bos birakirsan varsayilan kullanilir.', max_length=70, verbose_name='Google basligi (ana sayfa)'),
        ),
        migrations.CreateModel(
            name='ListingReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(max_length=1000, verbose_name='Sikayet metni')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('resolved', models.BooleanField(default=False, verbose_name='Cozuldu')),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='market.listing')),
                ('reporter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_made', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ilan sikayeti',
                'verbose_name_plural': 'Ilan sikayetleri',
                'ordering': ['resolved', '-created_at'],
            },
        ),
    ]
