# Generated by Django 5.2.17 on 2026-10-05 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0003_listing_video_order_payment_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='pending_review',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Onay bekliyor'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='moderate_new_listings',
            field=models.BooleanField(default=False, help_text="Acikken yeni ilanlar yayina girmeden once Ilanlar listesinde 'Onay bekliyor' olarak gorunur.", verbose_name='Yeni bireysel ilanlar yonetici onayindan gecsin'),
        ),
    ]
