# Generated by Django 5.2.17 on 2026-10-05 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0006_userblock'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='video_processed',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
