# Generated by Django 5.2.17 on 2026-10-05 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0007_listing_video_processed'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='translations',
            field=models.JSONField(blank=True, default=dict, help_text='Ornek: {"mk": {"title": "...", "body": "..."}}. Dil kodlari: en, mk, sq, sr, bg, el, bs.', verbose_name='Ceviriler'),
        ),
    ]
