# Generated by Django 5.2.17 on 2026-10-06 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0010_alter_listing_rating_alter_shop_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, help_text='Yuklenirse ana sayfa kutusunda simge yerine bu fotograf gorunur.', null=True, upload_to='categories/', verbose_name='Gorsel (istege bagli)'),
        ),
    ]
