# Generated by Django 5.2.17 on 2026-10-06 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0011_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='image_mobile',
            field=models.ImageField(blank=True, help_text='16:9 (orn. 1280x720). Bos birakirsan telefonda da web gorseli kullanilir.', null=True, upload_to='banners/', verbose_name='Gorsel (telefon / Android, istege bagli)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='meta_domain_verification',
            field=models.CharField(blank=True, help_text='Meta Business > Marka guvenligi > Alan adlari ekraninda verilen meta etiketi kodu.', max_length=80, verbose_name='Meta alan adi dogrulama kodu'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='meta_pixel_id',
            field=models.CharField(blank=True, help_text='Sadece rakamlar (orn. 123456789012345). Bos birakirsan piksel yuklenmez. Yalnizca cerez onayi veren ziyaretcilerde calisir.', max_length=20, verbose_name='Meta (Facebook/Instagram) Piksel kimligi'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.ImageField(upload_to='banners/', verbose_name='Gorsel (web / bilgisayar)'),
        ),
    ]
