# Generated by Django 5.2.17 on 2026-10-06 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0012_banner_image_mobile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='meta_pixel_early',
            field=models.BooleanField(default=False, help_text="Meta'nin 'piksel saptanmadi' kontrolu icin. Acikken fbevents.js onaydan once yuklenir ama Meta onay ('consent revoke') moduyla veri gondermez.", verbose_name='Meta onay modu: piksel kodunu hemen yukle, veri gonderimi onaya kadar dursun'),
        ),
    ]
