# Generated by Django 5.2.17 on 2026-10-07 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0014_stafftotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailystat',
            name='new_visitors',
            field=models.PositiveIntegerField(blank=True, help_text='Bos = eski kayit (tekrar eden ziyaretler ayrilamadi)', null=True, verbose_name='Ilk kez gelen kisi'),
        ),
        migrations.AlterField(
            model_name='dailystat',
            name='visitors',
            field=models.PositiveIntegerField(default=0, verbose_name='Bugunku tekil ziyaretci'),
        ),
    ]
