# Generated by Django 5.2.17 on 2026-10-09 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0015_dailystat_new_visitors_alter_dailystat_visitors'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='price_currency',
            field=models.CharField(blank=True, max_length=3),
        ),
        migrations.AddField(
            model_name='listing',
            name='price_input',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
