# Generated by Django 5.2.17 on 2026-10-09 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0016_listing_price_currency_listing_price_input'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='adsense_client',
            field=models.CharField(blank=True, help_text='Ornek: ca-pub-1234567890123456. AdSense onayi gelince girilir. Bos birakirsan Google reklami gosterilmez.', max_length=30, verbose_name='Google AdSense yayinci kimligi'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='adsense_slot',
            field=models.CharField(blank=True, help_text="160x600 dikey reklam biriminin sayisal kimligi. Yan sutunlarda kendi banner'in yoksa bu gosterilir.", max_length=20, verbose_name='AdSense yan sutun reklam birimi kimligi'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='place',
            field=models.CharField(choices=[('home_hero', 'Ana sayfa ust kaydirici (1400x420 onerilir)'), ('home_mid', 'Ana sayfa orta serit (600x300 onerilir, en fazla 3)'), ('side_l', 'Sol yan sutun (160x600, genis ekranlarda her sayfada)'), ('side_r', 'Sag yan sutun (160x600, genis ekranlarda her sayfada)')], default='home_hero', max_length=12, verbose_name='Alan'),
        ),
    ]
