# Generated by Django 5.2.17 on 2026-10-09 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0017_sitesettings_adsense_client_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='lang',
            field=models.CharField(blank=True, help_text='Uyenin kayit oldugu site dili; e-postalar bu dilde gider.', max_length=5, verbose_name='Dil'),
        ),
    ]
