# Generated by Django 5.2.17 on 2026-10-10 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0018_userprofile_lang'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='facebook_url',
            field=models.URLField(blank=True, help_text='Ornek: https://www.facebook.com/balkanbaazar . Bos birakirsan alt bilgide gorunmez.', verbose_name='Facebook sayfasi baglantisi'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='instagram_url',
            field=models.URLField(blank=True, help_text='Ornek: https://www.instagram.com/balkanbaazar', verbose_name='Instagram hesabi baglantisi'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='viber_url',
            field=models.URLField(blank=True, help_text='Viber toplulugu veya hesap baglantisi (https://...). Bos birakirsan gorunmez.', verbose_name='Viber baglantisi'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='whatsapp_url',
            field=models.URLField(blank=True, help_text='Ornek: https://whatsapp.com/channel/... Bos birakirsan gorunmez.', verbose_name='WhatsApp kanali baglantisi'),
        ),
    ]
