# Generated by Django 5.2.17 on 2026-10-10 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0019_sitesettings_facebook_url_sitesettings_instagram_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='viber_number',
            field=models.CharField(blank=True, help_text='Ulke koduyla yaz, ornek: +38970123456. Sitede GOSTERILMEZ; Viber dugmesine tiklayan kisi dogrudan sana yazar. Doluysa Viber baglantisindan once bu kullanilir.', max_length=20, verbose_name='Viber telefon numarasi'),
        ),
    ]
