# Generated by Django 5.2.17 on 2026-10-10 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0020_sitesettings_viber_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='district',
            field=models.CharField(blank=True, max_length=80, verbose_name='Ilce / mahalle'),
        ),
    ]
