# Generated by Django 5.2.17 on 2026-10-10 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0021_listing_district'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='expiry_warned',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name='listing',
            name='old_price_eur',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='old_price_input',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='price_dropped_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='sold',
            field=models.BooleanField(default=False, verbose_name='Satildi'),
        ),
    ]
