# -*- coding: utf-8 -*-
"""Hesap sayfalari ve kullanici uyari mesajlari (10 dil). Sira: tr, en, mk, sq, sr, bs, bg, el.
hr ve cnr, bs ile ayni Latin metni kullanir. Anahtarlar i18n.T icine eklenir (t.anahtar, msg(request, anahtar))."""

ORDER = ("tr", "en", "mk", "sq", "sr", "bs", "bg", "el")

DATA = {
# ---------------- uyari mesajlari ----------------
"m_form_fail": ("Form gönderilemedi, sayfayı yenileyip tekrar dene.", "The form could not be sent. Refresh the page and try again.", "Формуларот не можеше да се испрати. Освежи ја страницата и обиди се повторно.", "Formulari nuk u dërgua. Rifresko faqen dhe provo përsëri.", "Образац није послат. Освежи страницу и покушај поново.", "Obrazac nije poslan. Osvježi stranicu i pokušaj ponovo.", "Формулярът не беше изпратен. Обнови страницата и опитай отново.", "Η φόρμα δεν στάλθηκε. Ανανέωσε τη σελίδα και δοκίμασε ξανά."),
"m_acct_ready": ("Hesabın hazır. E-postanı doğrulamak için gelen kutuna bak. Mail görünmüyorsa Spam/Gereksiz klasörünü de kontrol et.", "Your account is ready. Check your inbox to verify your email. If you do not see it, check your Spam/Junk folder too.", "Профилот е подготвен. Провери го сандачето за да ја потврдиш е-поштата. Ако не го гледаш, провери и во Спам/Junk папката.", "Llogaria u krijua. Kontrollo kutinë postare për të verifikuar emailin. Nëse nuk e sheh, kontrollo edhe dosjen Spam/Junk.", "Налог је спреман. Провери пријемно сандуче да потврдиш имејл. Ако га не видиш, провери и Spam/Junk фасциклу.", "Račun je spreman. Provjeri inbox da potvrdiš e-poštu. Ako ga ne vidiš, provjeri i Spam/Junk mapu.", "Профилът е готов. Провери пощата си, за да потвърдиш имейла. Ако не го виждаш, провери и папката Спам/Junk.", "Ο λογαριασμός σου είναι έτοιμος. Έλεγξε τα εισερχόμενα για να επιβεβαιώσεις το email. Αν δεν το βλέπεις, έλεγξε και τον φάκελο Spam/Junk."),
"m_acct_ready_g": ("Hesabın hazır.", "Your account is ready.", "Профилот е подготвен.", "Llogaria u krijua.", "Налог је спреман.", "Račun je spreman.", "Профилът е готов.", "Ο λογαριασμός σου είναι έτοιμος."),
"m_product_saved": ("Ürün kaydedildi.", "Product saved.", "Производот е зачуван.", "Produkti u ruajt.", "Производ је сачуван.", "Proizvod je sačuvan.", "Продуктът е запазен.", "Το προϊόν αποθηκεύτηκε."),
"m_product_deleted": ("Ürün silindi.", "Product deleted.", "Производот е избришан.", "Produkti u fshi.", "Производ је обрисан.", "Proizvod je obrisan.", "Продуктът е изтрит.", "Το προϊόν διαγράφηκε."),
"m_shop_updated": ("Mağaza bilgileri güncellendi.", "Shop details updated.", "Податоците за продавницата се ажурирани.", "Të dhënat e dyqanit u përditësuan.", "Подаци о радњи су ажурирани.", "Podaci o trgovini su ažurirani.", "Данните за магазина са обновени.", "Τα στοιχεία του καταστήματος ενημερώθηκαν."),
"m_ship_saved": ("Kargo bilgisi kaydedildi.", "Shipping details saved.", "Податоците за испорака се зачувани.", "Të dhënat e dërgesës u ruajtën.", "Подаци о слању су сачувани.", "Podaci o slanju su sačuvani.", "Данните за доставка са запазени.", "Τα στοιχεία αποστολής αποθηκεύτηκαν."),
"m_profile_updated": ("Profil güncellendi.", "Profile updated.", "Профилот е ажуриран.", "Profili u përditësua.", "Профил је ажуриран.", "Profil je ažuriran.", "Профилът е обновен.", "Το προφίλ ενημερώθηκε."),
"m_pw_changed": ("Şifren değiştirildi.", "Your password was changed.", "Лозинката е променета.", "Fjalëkalimi u ndryshua.", "Лозинка је промењена.", "Lozinka je promijenjena.", "Паролата е сменена.", "Ο κωδικός σου άλλαξε."),
"m_shop_owner_delete": ("Mağaza sahibi hesaplar için silme talebini e-posta ile ilet.", "Shop owners should send account deletion requests by email.", "Сопствениците на продавници барањето за бришење го испраќаат по е-пошта.", "Pronarët e dyqaneve e dërgojnë kërkesën për fshirje me email.", "Власници радњи захтев за брисање шаљу имејлом.", "Vlasnici trgovina zahtjev za brisanje šalju e-poštom.", "Собствениците на магазини изпращат заявка за изтриване по имейл.", "Οι ιδιοκτήτες καταστημάτων στέλνουν το αίτημα διαγραφής με email."),
"m_verify_failed": ("Doğrulama başarısız.", "Verification failed.", "Потврдата не успеа.", "Verifikimi dështoi.", "Потврда није успела.", "Potvrda nije uspjela.", "Потвърждението не успя.", "Η επαλήθευση απέτυχε."),
"m_acct_deleted": ("Hesabın silindi.", "Your account was deleted.", "Профилот е избришан.", "Llogaria u fshi.", "Налог је обрисан.", "Račun je obrisan.", "Профилът е изтрит.", "Ο λογαριασμός σου διαγράφηκε."),
"m_verify_link_bad": ("Doğrulama bağlantısı geçersiz ya da süresi dolmuş.", "The verification link is invalid or has expired.", "Линкот за потврда е невалиден или истечен.", "Lidhja e verifikimit është e pavlefshme ose ka skaduar.", "Линк за потврду је неважећи или је истекао.", "Link za potvrdu je nevažeći ili je istekao.", "Връзката за потвърждение е невалидна или е изтекла.", "Ο σύνδεσμος επαλήθευσης δεν είναι έγκυρος ή έχει λήξει."),
"m_email_verified": ("E-postan doğrulandı.", "Your email is verified.", "Е-поштата е потврдена.", "Emaili u verifikua.", "Имејл је потврђен.", "E-pošta je potvrđena.", "Имейлът е потвърден.", "Το email επιβεβαιώθηκε."),
"m_verify_sent": ("Doğrulama e-postası gönderildi. Gelmediyse Spam/Gereksiz klasörüne bak.", "Verification email sent. If it does not arrive, check your Spam/Junk folder.", "Е-поштата за потврда е испратена. Ако не стигне, провери ја Спам/Junk папката.", "Emaili i verifikimit u dërgua. Nëse nuk vjen, kontrollo dosjen Spam/Junk.", "Имејл за потврду је послат. Ако не стигне, провери Spam/Junk фасциклу.", "E-pošta za potvrdu je poslana. Ako ne stigne, provjeri Spam/Junk mapu.", "Имейлът за потвърждение е изпратен. Ако не пристигне, провери папката Спам/Junk.", "Στάλθηκε email επιβεβαίωσης. Αν δεν φτάσει, έλεγξε τον φάκελο Spam/Junk."),
"m_doc_type": ("PDF, JPG veya PNG belge yükle.", "Upload a PDF, JPG or PNG document.", "Прикачи PDF, JPG или PNG документ.", "Ngarko dokument PDF, JPG ose PNG.", "Отпреми PDF, JPG или PNG документ.", "Učitaj PDF, JPG ili PNG dokument.", "Качи PDF, JPG или PNG документ.", "Ανέβασε έγγραφο PDF, JPG ή PNG."),
"m_doc_size": ("Belge en fazla 8 MB olabilir.", "The document can be at most 8 MB.", "Документот може да е најмногу 8 MB.", "Dokumenti mund të jetë deri në 8 MB.", "Документ може бити највише 8 MB.", "Dokument može imati najviše 8 MB.", "Документът може да е най-много 8 MB.", "Το έγγραφο μπορεί να είναι έως 8 MB."),
"m_verif_received": ("Başvurun alındı, inceleyip dönüş yapacağız.", "Request received. We will review it and get back to you.", "Барањето е примено. Ќе го прегледаме и ќе ти одговориме.", "Kërkesa u pranua. Do ta shqyrtojmë dhe do të të përgjigjemi.", "Захтев је примљен. Прегледаћемо га и јавити ти се.", "Zahtjev je primljen. Pregledat ćemo ga i javiti ti se.", "Заявката е получена. Ще я прегледаме и ще ти отговорим.", "Το αίτημα ελήφθη. Θα το εξετάσουμε και θα σου απαντήσουμε."),
"m_g_fail": ("Google girişi tamamlanamadı, tekrar dene.", "Google sign-in could not be completed. Please try again.", "Најавата со Google не успеа. Обиди се повторно.", "Hyrja me Google nuk u krye. Provo përsëri.", "Пријава преко Google-а није успела. Покушај поново.", "Prijava preko Googlea nije uspjela. Pokušaj ponovo.", "Влизането с Google не успя. Опитай отново.", "Η σύνδεση με Google δεν ολοκληρώθηκε. Δοκίμασε ξανά."),
"m_g_conn": ("Google ile bağlantı kurulamadı.", "Could not connect to Google.", "Не успеа врската со Google.", "Nuk u lidh me Google.", "Није успело повезивање са Google-ом.", "Nije uspjelo povezivanje s Googleom.", "Връзката с Google не успя.", "Δεν έγινε σύνδεση με το Google."),
"m_g_unverified": ("Google hesabının e-postası doğrulanmamış.", "The email of your Google account is not verified.", "Е-поштата на твојот Google профил не е потврдена.", "Emaili i llogarisë Google nuk është verifikuar.", "Имејл твог Google налога није потврђен.", "E-pošta tvog Google računa nije potvrđena.", "Имейлът на твоя Google профил не е потвърден.", "Το email του λογαριασμού Google δεν είναι επιβεβαιωμένο."),
"m_need_verify": ("İlan vermek için önce e-postanı doğrulaman gerekiyor.", "You need to verify your email before posting an ad.", "За да објавиш оглас, прво потврди ја е-поштата.", "Për të publikuar shpallje, verifiko fillimisht emailin.", "Да би објавио оглас, прво потврди имејл.", "Da bi objavio oglas, prvo potvrdi e-poštu.", "За да публикуваш обява, първо потвърди имейла си.", "Για να δημοσιεύσεις αγγελία, επιβεβαίωσε πρώτα το email σου."),
"m_listing_published": ("İlan yayınlandı.", "Your ad is published.", "Огласот е објавен.", "Shpallja u publikua.", "Оглас је објављен.", "Oglas je objavljen.", "Обявата е публикувана.", "Η αγγελία δημοσιεύτηκε."),
"m_listing_updated": ("İlan güncellendi.", "Your ad was updated.", "Огласот е ажуриран.", "Shpallja u përditësua.", "Оглас је ажуриран.", "Oglas je ažuriran.", "Обявата е обновена.", "Η αγγελία ενημερώθηκε."),
"m_listing_deleted": ("İlan silindi.", "Your ad was deleted.", "Огласот е избришан.", "Shpallja u fshi.", "Оглас је обрисан.", "Oglas je obrisan.", "Обявата е изтрита.", "Η αγγελία διαγράφηκε."),
"m_pick_option": ("Lütfen önce bir seçenek (beden/renk) seç.", "Please choose an option (size/colour) first.", "Прво избери опција (големина/боја).", "Zgjidh fillimisht një opsion (madhësi/ngjyrë).", "Прво изабери опцију (величина/боја).", "Prvo odaberi opciju (veličina/boja).", "Първо избери опция (размер/цвят).", "Διάλεξε πρώτα μια επιλογή (μέγεθος/χρώμα)."),
"m_option_oos": ("Bu seçenek stokta yok.", "This option is out of stock.", "Оваа опција нема на залиха.", "Ky opsion nuk është në stok.", "Ова опција није на залихама.", "Ova opcija nije na zalihi.", "Тази опция не е налична.", "Αυτή η επιλογή δεν είναι διαθέσιμη."),
"m_out_of_stock": ("Bu ürün şu anda stokta yok.", "This product is currently out of stock.", "Овој производ моментално го нема на залиха.", "Ky produkt nuk është aktualisht në stok.", "Овај производ тренутно није на залихама.", "Ovaj proizvod trenutno nije na zalihi.", "Този продукт в момента не е наличен.", "Αυτό το προϊόν δεν είναι διαθέσιμο αυτή τη στιγμή."),
"m_added_cart": ("{title} sepete eklendi.", "{title} was added to the cart.", "{title} е додадено во кошничката.", "{title} u shtua në shportë.", "{title} је додато у корпу.", "{title} je dodano u korpu.", "{title} е добавено в количката.", "Το {title} προστέθηκε στο καλάθι."),
"m_stock_short": ("{title}: yeterli stok kalmadı.", "{title}: not enough stock left.", "{title}: нема доволно залиха.", "{title}: nuk ka stok të mjaftueshëm.", "{title}: нема довољно залиха.", "{title}: nema dovoljno zaliha.", "{title}: няма достатъчно наличност.", "{title}: δεν υπάρχει αρκετό απόθεμα."),
"m_pay_fail": ("Ödeme başlatılamadı, lütfen tekrar dene.", "Payment could not be started. Please try again.", "Плаќањето не можеше да започне. Обиди се повторно.", "Pagesa nuk filloi. Provo përsëri.", "Плаћање није покренуто. Покушај поново.", "Plaćanje nije pokrenuto. Pokušaj ponovo.", "Плащането не можа да започне. Опитай отново.", "Η πληρωμή δεν ξεκίνησε. Δοκίμασε ξανά."),
"m_order_cancelled": ("Siparişin iptal edildi.", "Your order was cancelled.", "Нарачката е откажана.", "Porosia u anulua.", "Поруџбина је отказана.", "Narudžba je otkazana.", "Поръчката е отказана.", "Η παραγγελία ακυρώθηκε."),
"m_user_blocked": ("Kullanıcı engellendi.", "User blocked.", "Корисникот е блокиран.", "Përdoruesi u bllokua.", "Корисник је блокиран.", "Korisnik je blokiran.", "Потребителят е блокиран.", "Ο χρήστης αποκλείστηκε."),
"m_msg_unavailable": ("Bu ilan için mesajlaşma şu anda kullanılamıyor.", "Messaging is not available for this ad right now.", "Пораките за овој оглас моментално не се достапни.", "Mesazhet për këtë shpallje nuk janë të disponueshme tani.", "Поруке за овај оглас тренутно нису доступне.", "Poruke za ovaj oglas trenutno nisu dostupne.", "Съобщенията за тази обява в момента не са налични.", "Η αποστολή μηνυμάτων για αυτή την αγγελία δεν είναι διαθέσιμη τώρα."),
"m_cannot_msg": ("Bu kullanıcı ile mesajlaşamazsın.", "You cannot message this user.", "Не можеш да пишуваш на овој корисник.", "Nuk mund t'i shkruash këtij përdoruesi.", "Не можеш да пишеш овом кориснику.", "Ne možeš pisati ovom korisniku.", "Не можеш да пишеш на този потребител.", "Δεν μπορείς να στείλεις μήνυμα σε αυτόν τον χρήστη."),
"m_no_chat_access": ("Bu sohbete erişimin yok.", "You do not have access to this conversation.", "Немаш пристап до овој разговор.", "Nuk ke qasje në këtë bisedë.", "Немаш приступ овом разговору.", "Nemaš pristup ovom razgovoru.", "Нямаш достъп до този разговор.", "Δεν έχεις πρόσβαση σε αυτή τη συνομιλία."),
"m_msg_rate": ("Çok hızlı mesaj gönderiyorsun, biraz bekle.", "You are sending messages too fast. Please wait a moment.", "Праќаш пораки премногу брзо. Почекај малку.", "Po dërgon mesazhe shumë shpejt. Prit pak.", "Шаљеш поруке пребрзо. Сачекај мало.", "Šalješ poruke prebrzo. Pričekaj malo.", "Изпращаш съобщения твърде бързо. Изчакай малко.", "Στέλνεις μηνύματα πολύ γρήγορα. Περίμενε λίγο."),
"m_cannot_boost": ("Bu ilanı öne çıkaramazsın.", "You cannot promote this ad.", "Не можеш да го истакнеш овој оглас.", "Nuk mund ta promovosh këtë shpallje.", "Не можеш да истакнеш овај оглас.", "Ne možeš istaknuti ovaj oglas.", "Не можеш да подчертаеш тази обява.", "Δεν μπορείς να προωθήσεις αυτή την αγγελία."),
"m_bad_pack": ("Geçersiz paket.", "Invalid package.", "Невалиден пакет.", "Paketë e pavlefshme.", "Неважећи пакет.", "Nevažeći paket.", "Невалиден пакет.", "Μη έγκυρο πακέτο."),
"m_boosted": ("{title} {days} gün süreyle öne çıkarıldı.", "{title} is promoted for {days} days.", "{title} е истакнат {days} дена.", "{title} u promovua për {days} ditë.", "{title} је истакнут {days} дана.", "{title} je istaknut {days} dana.", "{title} е подчертана за {days} дни.", "Το {title} προωθείται για {days} ημέρες."),
"m_review_thanks": ("Yorumun için teşekkürler.", "Thanks for your review.", "Благодариме за коментарот.", "Faleminderit për komentin.", "Хвала на коментару.", "Hvala na komentaru.", "Благодарим за коментара.", "Ευχαριστούμε για το σχόλιο."),
"m_report_thanks": ("Şikâyetin alındı, teşekkürler.", "Your report was received. Thank you.", "Пријавата е примена. Благодариме.", "Raportimi u pranua. Faleminderit.", "Пријава је примљена. Хвала.", "Prijava je primljena. Hvala.", "Сигналът е получен. Благодарим.", "Η αναφορά ελήφθη. Ευχαριστούμε."),
"m_report_empty": ("Lütfen şikâyet metnini yaz.", "Please describe your report.", "Опиши ја пријавата.", "Shkruaj përshkrimin e raportit.", "Опиши своју пријаву.", "Opiši svoju prijavu.", "Опиши сигнала си.", "Περίγραψε την αναφορά σου."),
"m_listing_renewed": ("İlan yenilendi.", "Your ad was renewed.", "Огласот е обновен.", "Shpallja u rinovua.", "Оглас је обновљен.", "Oglas je obnovljen.", "Обявата е подновена.", "Η αγγελία ανανεώθηκε."),
"m_max_saved": ("En fazla 10 arama kaydedebilirsin.", "You can save up to 10 searches.", "Можеш да зачуваш најмногу 10 пребарувања.", "Mund të ruash deri në 10 kërkime.", "Можеш да сачуваш највише 10 претрага.", "Možeš spremiti najviše 10 pretraga.", "Можеш да запазиш най-много 10 търсения.", "Μπορείς να αποθηκεύσεις έως 10 αναζητήσεις."),
"m_search_saved": ("Arama kaydedildi. Yeni ilan gelince haber vereceğiz.", "Search saved. We will let you know about new ads.", "Пребарувањето е зачувано. Ќе те известиме за нови огласи.", "Kërkimi u ruajt. Do të njoftojmë për shpallje të reja.", "Претрага је сачувана. Обавестићемо те о новим огласима.", "Pretraga je spremljena. Obavijestit ćemo te o novim oglasima.", "Търсенето е запазено. Ще те уведомим за нови обяви.", "Η αναζήτηση αποθηκεύτηκε. Θα σε ενημερώσουμε για νέες αγγελίες."),
"m_seller_review_saved": ("Değerlendirmen kaydedildi, teşekkürler.", "Your rating was saved. Thank you.", "Оцената е зачувана. Благодариме.", "Vlerësimi u ruajt. Faleminderit.", "Оцена је сачувана. Хвала.", "Ocjena je spremljena. Hvala.", "Оценката е запазена. Благодарим.", "Η βαθμολογία αποθηκεύτηκε. Ευχαριστούμε."),
# ---------------- hesap sayfalari ----------------
"a_pw_short": ("Şifre", "Password", "Лозинка", "Fjalëkalimi", "Лозинка", "Lozinka", "Парола", "Κωδικός"),
"a_change_pw": ("Şifremi değiştir", "Change my password", "Промени ја лозинката", "Ndrysho fjalëkalimin", "Промени лозинку", "Promijeni lozinku", "Смени паролата", "Αλλαγή κωδικού"),
"a_del_acct": ("Hesabımı sil", "Delete my account", "Избриши го профилот", "Fshi llogarinë", "Обриши налог", "Obriši račun", "Изтрий профила", "Διαγραφή λογαριασμού"),
"a_unverified_p": ("E-posta adresin henüz doğrulanmadı. İlan verebilmek için doğrulaman gerekiyor.", "Your email is not verified yet. You need to verify it to post ads.", "Е-поштата сè уште не е потврдена. Мора да ја потврдиш за да објавуваш огласи.", "Emaili nuk është verifikuar ende. Duhet ta verifikosh për të publikuar shpallje.", "Имејл још није потврђен. Мораш га потврдити да би објављивао огласе.", "E-pošta još nije potvrđena. Moraš je potvrditi da bi objavljivao oglase.", "Имейлът още не е потвърден. Трябва да го потвърдиш, за да публикуваш обяви.", "Το email δεν έχει επιβεβαιωθεί ακόμα. Πρέπει να το επιβεβαιώσεις για να δημοσιεύεις αγγελίες."),
"a_send_verify": ("Doğrulama e-postasını gönder", "Send verification email", "Испрати е-пошта за потврда", "Dërgo emailin e verifikimit", "Пошаљи имејл за потврду", "Pošalji e-poštu za potvrdu", "Изпрати имейл за потвърждение", "Αποστολή email επιβεβαίωσης"),
"a_pw_change_t": ("Şifre değiştir", "Change password", "Промена на лозинка", "Ndrysho fjalëkalimin", "Промена лозинке", "Promjena lozinke", "Смяна на парола", "Αλλαγή κωδικού"),
"a_pw_new_t": ("Yeni şifre belirle", "Set a new password", "Постави нова лозинка", "Vendos fjalëkalim të ri", "Постави нову лозинку", "Postavi novu lozinku", "Задай нова парола", "Όρισε νέο κωδικό"),
"a_pw_save": ("Şifreyi kaydet", "Save password", "Зачувај лозинка", "Ruaj fjalëkalimin", "Сачувај лозинку", "Spremi lozinku", "Запази паролата", "Αποθήκευση κωδικού"),
"a_link_bad_t": ("Bağlantı geçersiz", "Invalid link", "Невалиден линк", "Lidhje e pavlefshme", "Неважећи линк", "Nevažeći link", "Невалидна връзка", "Μη έγκυρος σύνδεσμος"),
"a_link_bad_p": ("Bu bağlantının süresi dolmuş ya da daha önce kullanılmış.", "This link has expired or was already used.", "Овој линк е истечен или веќе е употребен.", "Kjo lidhje ka skaduar ose është përdorur tashmë.", "Овај линк је истекао или је већ коришћен.", "Ovaj link je istekao ili je već korišten.", "Тази връзка е изтекла или вече е използвана.", "Ο σύνδεσμος έχει λήξει ή έχει ήδη χρησιμοποιηθεί."),
"a_link_new": ("Yeni bağlantı iste", "Request a new link", "Побарај нов линк", "Kërko lidhje të re", "Затражи нови линк", "Zatraži novi link", "Поискай нова връзка", "Ζήτησε νέο σύνδεσμο"),
"a_pw_done_t": ("Şifren değiştirildi", "Your password was changed", "Лозинката е променета", "Fjalëkalimi u ndryshua", "Лозинка је промењена", "Lozinka je promijenjena", "Паролата е сменена", "Ο κωδικός άλλαξε"),
"a_chk_mail_t": ("E-postanı kontrol et", "Check your email", "Провери ја е-поштата", "Kontrollo emailin", "Провери имејл", "Provjeri e-poštu", "Провери имейла си", "Έλεγξε το email σου"),
"a_chk_mail_p": ("Bu adres kayıtlıysa şifre sıfırlama bağlantısı gönderildi. Gelmediyse spam klasörüne bak.", "If this address is registered, we sent a password reset link. Check your spam folder if it does not arrive.", "Ако адресата е регистрирана, испративме линк за ресетирање. Ако не стигне, провери го спамот.", "Nëse adresa është e regjistruar, dërguam një lidhje rivendosjeje. Nëse nuk vjen, shiko te spam.", "Ако је адреса регистрована, послали смо линк за ресетовање. Ако не стигне, провери спам.", "Ako je adresa registrirana, poslali smo link za resetiranje. Ako ne stigne, provjeri spam.", "Ако адресът е регистриран, изпратихме връзка за нулиране. Ако не пристигне, провери спама.", "Αν η διεύθυνση είναι εγγεγραμμένη, στείλαμε σύνδεσμο επαναφοράς. Αν δεν φτάσει, δες τα spam."),
"a_back_login": ("Girişe dön", "Back to sign in", "Назад кон најава", "Kthehu te hyrja", "Назад на пријаву", "Natrag na prijavu", "Назад към вход", "Πίσω στη σύνδεση"),
"a_pw_reset_t": ("Şifre sıfırla", "Reset password", "Ресетирај лозинка", "Rivendos fjalëkalimin", "Ресетуј лозинку", "Resetiraj lozinku", "Нулирай парола", "Επαναφορά κωδικού"),
"a_pw_reset_p": ("Kayıtlı e-posta adresini yaz, sana şifre sıfırlama bağlantısı gönderelim.", "Enter your registered email and we will send you a password reset link.", "Внеси ја регистрираната е-пошта и ќе ти испратиме линк за ресетирање.", "Shkruaj emailin e regjistruar dhe do të dërgojmë një lidhje rivendosjeje.", "Унеси регистровани имејл и послаћемо ти линк за ресетовање.", "Unesi registriranu e-poštu i poslat ćemo ti link za resetiranje.", "Въведи регистрирания си имейл и ще ти изпратим връзка за нулиране.", "Γράψε το email σου και θα σου στείλουμε σύνδεσμο επαναφοράς."),
"a_send_link": ("Bağlantı gönder", "Send link", "Испрати линк", "Dërgo lidhjen", "Пошаљи линк", "Pošalji link", "Изпрати връзка", "Αποστολή συνδέσμου"),
"a_del_t": ("Hesabı sil", "Delete account", "Бришење на профил", "Fshi llogarinë", "Брисање налога", "Brisanje računa", "Изтриване на профил", "Διαγραφή λογαριασμού"),
"a_del_p": ("Hesabın kapatılır, kişisel bilgilerin (ad, e-posta) silinir ve ilanların yayından kaldırılır. Bu işlem geri alınamaz.", "Your account will be closed, your personal data (name, email) deleted and your ads removed. This cannot be undone.", "Профилот се затвора, личните податоци (име, е-пошта) се бришат, а огласите се отстрануваат. Ова не може да се врати.", "Llogaria mbyllet, të dhënat personale (emri, emaili) fshihen dhe shpalljet hiqen. Kjo nuk kthehet.", "Налог се затвара, лични подаци (име, имејл) се бришу, а огласи се уклањају. Ово се не може поништити.", "Račun se zatvara, osobni podaci (ime, e-pošta) brišu se, a oglasi uklanjaju. Ovo se ne može poništiti.", "Профилът се закрива, личните данни (име, имейл) се изтриват, а обявите се премахват. Това не може да се върне.", "Ο λογαριασμός κλείνει, τα προσωπικά στοιχεία (όνομα, email) διαγράφονται και οι αγγελίες αφαιρούνται. Δεν αναιρείται."),
"a_pw_label": ("Şifren", "Your password", "Твојата лозинка", "Fjalëkalimi yt", "Твоја лозинка", "Tvoja lozinka", "Твоята парола", "Ο κωδικός σου"),
"a_del_email": ("Onay için e-posta adresini yaz", "Type your email address to confirm", "Напиши ја е-поштата за потврда", "Shkruaj emailin për konfirmim", "Упиши имејл ради потврде", "Upiši e-poštu radi potvrde", "Въведи имейла си за потвърждение", "Γράψε το email σου για επιβεβαίωση"),
"a_del_btn": ("Hesabımı kalıcı olarak sil", "Delete my account permanently", "Избриши го профилот засекогаш", "Fshi llogarinë përgjithmonë", "Трајно обриши налог", "Trajno obriši račun", "Изтрий профила завинаги", "Διαγραφή λογαριασμού οριστικά"),
"a_cancel": ("Vazgeç", "Cancel", "Откажи", "Anulo", "Откажи", "Odustani", "Отказ", "Ακύρωση"),
"a_ver_review": ("Başvurun inceleniyor.", "Your request is under review.", "Барањето се прегледува.", "Kërkesa po shqyrtohet.", "Захтев се прегледа.", "Zahtjev se pregledava.", "Заявката се преглежда.", "Το αίτημα εξετάζεται."),
"a_ver_rejected": ("Önceki başvuru onaylanmadı.", "The previous request was not approved.", "Претходното барање не беше одобрено.", "Kërkesa e mëparshme nuk u miratua.", "Претходни захтев није одобрен.", "Prethodni zahtjev nije odobren.", "Предишната заявка не беше одобрена.", "Το προηγούμενο αίτημα δεν εγκρίθηκε."),
"a_ver_info": ("Doğrulanmış mağazalar ✔ rozeti alır ve alıcıların güvenini kazanır. Şirket kayıt belgeni, vergi levhanı ya da kimlik belgeni yükle (PDF, JPG, PNG, en fazla 8 MB). Belgeler herkese kapalı saklanır ve sadece doğrulama için incelenir.", "Verified shops get a ✔ badge and buyers' trust. Upload your company registration, tax certificate or ID (PDF, JPG, PNG, max 8 MB). Documents are stored privately and used for verification only.", "Верифицираните продавници добиваат ✔ значка и доверба од купувачите. Прикачи регистрација на фирма, даночно уверение или лична карта (PDF, JPG, PNG, најмногу 8 MB). Документите се чуваат приватно и се користат само за верификација.", "Dyqanet e verifikuara marrin shenjën ✔ dhe besimin e blerësve. Ngarko regjistrimin e kompanisë, certifikatën tatimore ose ID (PDF, JPG, PNG, deri në 8 MB). Dokumentet ruhen privatisht dhe përdoren vetëm për verifikim.", "Верификоване радње добијају ✔ ознаку и поверење купаца. Отпреми регистрацију фирме, пореско уверење или личну карту (PDF, JPG, PNG, највише 8 MB). Документи се чувају приватно и користе само за верификацију.", "Verificirane trgovine dobivaju ✔ oznaku i povjerenje kupaca. Učitaj registraciju firme, porezno uvjerenje ili osobnu iskaznicu (PDF, JPG, PNG, najviše 8 MB). Dokumenti se čuvaju privatno i koriste samo za verifikaciju.", "Верифицираните магазини получават ✔ значка и доверие от купувачите. Качи регистрация на фирмата, данъчно удостоверение или лична карта (PDF, JPG, PNG, до 8 MB). Документите се съхраняват поверително и се ползват само за верификация.", "Τα επαληθευμένα καταστήματα παίρνουν σήμα ✔ και την εμπιστοσύνη των αγοραστών. Ανέβασε εγγραφή εταιρείας, φορολογικό πιστοποιητικό ή ταυτότητα (PDF, JPG, PNG, έως 8 MB). Τα έγγραφα φυλάσσονται ιδιωτικά και χρησιμοποιούνται μόνο για επαλήθευση."),
"a_ver_doc": ("Belge", "Document", "Документ", "Dokumenti", "Документ", "Dokument", "Документ", "Έγγραφο"),
"a_ver_note": ("Not", "Note", "Белешка", "Shënim", "Напомена", "Napomena", "Бележка", "Σημείωση"),
"a_ver_submit": ("Gönder", "Submit", "Испрати", "Dërgo", "Пошаљи", "Pošalji", "Изпрати", "Υποβολή"),
}


def build():
    """{dil: {anahtar: metin}} -- hr ve cnr, bs'ten kopyalanir."""
    out = {code: {} for code in ORDER + ("hr", "cnr")}
    for key, texts in DATA.items():
        assert len(texts) == len(ORDER), key
        for code, text in zip(ORDER, texts):
            out[code][key] = text
        out["hr"][key] = out["cnr"][key] = out["bs"][key]
    return out
